### ISSUE TITLE
Option for Custom APIM Developer Portal (self-hosted)

### ISSUE THREAD

**Issue by alanamircruz** [claranet/terraform-azurerm-api-management#2]
Hello Team,

I hope that everything is going great. Thanks for your effort on this very needed module, so I have a question please.

* Is there a way that we can set up a provided (self-hosted) API Developer Portal for an API using this module ?, I saw the option ` developer_portal_hostname_configuration`, but I am not sure if this can help with it.

Thanks for any info regarding this one, have a great day ahead.
Alan

**Comment by BzSpi** [comment]
Hello @alanamircruz the attribute you're pointing is to configure custom domains on your API Management.

Self hosted developer portal is not related to the API Management deployment.

You can find the related documentation here: https://docs.microsoft.com/en-us/azure/api-management/developer-portal-self-host

**Comment by alanamircruz** [comment]
Thanks for your time @BzSpi and info/answer. Have a great week ahead, merci
